### ISSUE TITLE
Unable to uninstall

### ISSUE THREAD

**Issue by FelixFourcolor** [icedman/custom-window-controls#5]
After uninstalling the extension, the buttons do not return to gnome's default. Please help.

Gnome 45

EDIT: For others who have similar issues, I found a manual solution: removing `~/.config/gtk-3.0` and `~/.config/gtk-4.0`.

**Comment by icedman** [comment]
Or disable before uninstalling.

**Comment by nonstandardusr** [comment]
> Or disable before uninstalling.

This doesn't work. I was only able to return to the default after removing the `gtk.css` files in the 3.0 and 4.0 folders. In fact, **even after disabling the extension or removing it, the styling (shape of the buttons, traffic light colors) remained.**

This seems to suggest the javascript code that enables the traffic light colors and whatnot are still running somewhere somehow, which means that even if I remove the css files, there's remnants of this extension on my computer; just not triggered anymore because I removed the css files.

I don't know if I should raise a new issue regarding this behavior, so I'll just hijack this issue thread to get this out to you; given, of course, you are interested in maintaining this extension. Also, as a side note, this didn't seem to work on flatpak apps.

**Comment by icedman** [comment]
Disable function did have an error and could not complete all the tasks. Thanks for the info.
Branch g45 now has this issue fixed.

**Comment by FelixFourcolor** [comment]
@icedman I no longer have my gnome setup in order to test, so feel free to close the issue if you think it has been resolved.
